-- Imovel ={}
-- Imovel.__index = Imovel

-- function Imovel:novo(tipo,identificador,dono)
--    local imov = {}             
--    setmetatable(imov,Imovel)
--    imov.tipo=tipo 
--    imov.identificador = identificador
--    imov.dono=dono
--    return imov
-- end
-- function Imovel:imprime()
--     print(self.tipo)
-- end
-- return Imovel 
